// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaKIzJLDugar1GCVFWlXP52Plk3fFswzU',
    appId: '1:44861435796:web:a5a90d3543dc877f02e981',
    messagingSenderId: '44861435796',
    projectId: 'salon-manager-205db',
    authDomain: 'salon-manager-205db.firebaseapp.com',
    storageBucket: 'salon-manager-205db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAatdp3o96y6CtygBYJk-4wAr7GwGA3aXY',
    appId: '1:44861435796:android:2adee197a144b3cf02e981',
    messagingSenderId: '44861435796',
    projectId: 'salon-manager-205db',
    storageBucket: 'salon-manager-205db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBLYBjiO-SBKa6oFjYesRI_hL5bHX9fOw',
    appId: '1:44861435796:ios:eedee8b3502e4bb402e981',
    messagingSenderId: '44861435796',
    projectId: 'salon-manager-205db',
    storageBucket: 'salon-manager-205db.appspot.com',
    iosClientId: '44861435796-og8tf0gkkmj54a8tkfagero5npvnj3bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBLYBjiO-SBKa6oFjYesRI_hL5bHX9fOw',
    appId: '1:44861435796:ios:eedee8b3502e4bb402e981',
    messagingSenderId: '44861435796',
    projectId: 'salon-manager-205db',
    storageBucket: 'salon-manager-205db.appspot.com',
    iosClientId: '44861435796-og8tf0gkkmj54a8tkfagero5npvnj3bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonManager',
  );
}
